apiVersion: v1
kind: Service
metadata:
    name: "aksassutademo-5993"
    labels:
        app: "aksassutademo-5993"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksassutademo-5993"